fix update script

diff --git a/pack/plugins/start/update-git b/pack/plugins/start/update-git
--- a/pack/plugins/start/update-git
+++ b/pack/plugins/start/update-git
@@ -2,25 +2,24 @@
 set -uo pipefail
 
 declare -r script="$(readlink -f "${BASH_SOURCE[0]}")"
-declare -r script_dir="$(dirname $script)"
+declare -r script_dir="$(dirname "$script")"
 . "$script_dir"/library.bash
 
 skip=(
-        'YouCompleteMe'
-        'snippets'
+        git-YouCompleteMe
+        git-vim-airline
      )
 
 for d in *; do
+    [[ -e "$d/.git" ]] || continue
+    print "$d"
+
     for skip_item in "${skip[@]}"; do
-        declare -r re='.*'"$skip_item"'.*'
-        if [[ "$d" =~ $re ]]; then
+        if [[ "$d" == "$skip_item" ]]; then
             echo "skipping $d"
             continue 2
         fi
     done
 
-    [[ -e "$d/.git" ]] || continue
-
-    print $d
-    ( cd $d && git pull || git pull origin master ) || { echo "failed to upgrade $d "; exit 1; }
+    ( cd "$d" && git pull || git pull origin master ) || { echo "failed to upgrade $d "; exit 0; }
 done
